package wire

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"arrasgo/internal/entity"
	"arrasgo/internal/net"
)

// The HUD is verified against vectors generated by tools/gen-gui-vectors.js from the shipped JS.

type guiVectors struct {
	Cases []guiCase `json:"cases"`
}

type guiCase struct {
	Name            string     `json:"name"`
	Note            string     `json:"note"`
	Frames          []guiFrame `json:"frames"`
	SkippedUpgrades []int32    `json:"skippedUpgrades"`
}

type guiFrame struct {
	Input     guiVectorInput    `json:"input"`
	Published []json.RawMessage `json:"published"`
}

type guiVectorInput struct {
	TeamColor       string             `json:"teamColor"`
	BodyID          float64            `json:"bodyID"`
	Index           string             `json:"index"`
	Score           float64            `json:"score"`
	Solo            float64            `json:"solo"`
	Assists         float64            `json:"assists"`
	Bosses          float64            `json:"bosses"`
	Points          float64            `json:"points"`
	Level           int32              `json:"level"`
	UpgradePending  bool               `json:"upgradePending"`
	Upgrades        []guiVectorUpgrade `json:"upgrades"`
	Titles          []string           `json:"titles"`
	Caps            []float64          `json:"caps"`
	SoftCaps        []float64          `json:"softCaps"`
	Amounts         []float64          `json:"amounts"`
	Accel           float64            `json:"accel"`
	TopSpeed        float64            `json:"topSpeed"`
	Root            *string            `json:"root"`
	Class           string             `json:"class"`
	CanSeeInvisible bool               `json:"canSeeInvisible"`
	DailyTankJSON   string             `json:"dailyTankJSON"`
}

// BranchLabel is a pointer because null and "" are different on the wire.
type guiVectorUpgrade struct {
	Branch      int32   `json:"branch"`
	BranchLabel *string `json:"branchLabel"`
	Index       string  `json:"index"`
	Level       int32   `json:"level"`
}

func loadGUIVectors(t *testing.T) guiVectors {
	t.Helper()
	path := filepath.Join("..", "..", "gen", "gui-vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run: node tools/gen-gui-vectors.js)", path, err)
	}
	var v guiVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	if len(v.Cases) == 0 {
		t.Fatalf("%s carries no cases", path)
	}
	return v
}

func (in *guiVectorInput) toGUIInput() guiInput {
	out := guiInput{
		// global.fps is "Unknown" until the speed loop runs, and this port has
		// no speed loop. The generator holds it there too.
		fps:             math.NaN(),
		teamColor:       in.TeamColor,
		bodyID:          in.BodyID,
		index:           in.Index,
		score:           in.Score,
		solo:            in.Solo,
		assists:         in.Assists,
		bosses:          in.Bosses,
		points:          in.Points,
		level:           in.Level,
		upgradePending:  in.UpgradePending,
		accel:           in.Accel,
		topSpeed:        in.TopSpeed,
		class:           in.Class,
		canSeeInvisible: in.CanSeeInvisible,
		dailyTankJSON:   in.DailyTankJSON,
	}
	if in.Root != nil {
		out.root, out.hasRoot = *in.Root, true
	}
	for _, u := range in.Upgrades {
		row := entity.Upgrade{Branch: u.Branch, Index: u.Index, Level: u.Level}
		if u.BranchLabel != nil {
			row.BranchLabel, row.HasBranchLabel = *u.BranchLabel, true
		}
		out.upgrades = append(out.upgrades, row)
	}
	copy(out.titles[:], in.Titles)
	copy(out.caps[:], in.Caps)
	copy(out.softCaps[:], in.SoftCaps)
	copy(out.amounts[:], in.Amounts)
	return out
}

func TestGUIBlockMatchesTheJS(t *testing.T) {
	vectors := loadGUIVectors(t)
	for _, c := range vectors.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			g := newGUIState()
			var skips []int32
			for i, frame := range c.Frames {
				in := frame.Input.toGUIInput()
				g.update(&in)
				if g.wroteSkips {
					skips = append(skips[:0], g.skipBuf...)
				}
				var block net.GUIBlock
				publishInto(g, &block, in.teamColor)
				got := block.Append(nil)
				want := frame.Published
				if len(got) != len(want) {
					t.Fatalf("frame %d has %d values, want %d\n got: %s\nwant: %s",
						i, len(got), len(want), showValues(got), showRaw(want))
				}
				for j := range got {
					if !valueMatches(got[j], want[j]) {
						t.Fatalf("frame %d value %d is %v, want %s\n got: %s\nwant: %s",
							i, j, got[j], want[j], showValues(got), showRaw(want))
					}
				}
			}
			if c.SkippedUpgrades != nil {
				if len(skips) != len(c.SkippedUpgrades) {
					t.Fatalf("skippedUpgrades is %v, want %v", skips, c.SkippedUpgrades)
				}
				for i := range skips {
					if skips[i] != c.SkippedUpgrades[i] {
						t.Fatalf("skippedUpgrades is %v, want %v", skips, c.SkippedUpgrades)
					}
				}
			}
		})
	}
}

// publishInto is publishGUI without a socket. The one thing the socket supplies
// is the team colour the label branch falls back to.
func publishInto(g *guiState, out *net.GUIBlock, teamColor string) {
	if v, ok := g.fps.publish(); ok {
		out.HasFPS, out.FPS = true, v
	}
	colour, hasColour := g.colour.publish()
	if v, ok := g.label.publish(); ok {
		out.HasLabel, out.Label, out.BodyID = true, v, g.bodyID
		if hasColour && colour != "" {
			out.Color = colour
		} else {
			out.Color = teamColor
		}
	}
	if v, ok := g.score.publish(); ok {
		out.HasScore, out.ScoreJSON = true, v
	}
	if v, ok := g.points.publish(); ok {
		out.HasPoints, out.Points = true, v
	}
	if v, ok := g.upgrades.publish(); ok {
		out.HasUpgrades, out.Upgrades = true, v
	}
	g.stats.publish(out)
	if v, ok := g.skills.publish(); ok {
		out.HasSkills, out.Skills = true, v
	}
	if v, ok := g.accel.publish(); ok {
		out.HasAccel, out.Accel = true, v
	}
	if v, ok := g.topSpeed.publish(); ok {
		out.HasTopSpeed, out.TopSpeed = true, v
	}
	if v, ok := g.root.publish(); ok {
		out.HasRoot, out.Root = true, v
	}
	if v, ok := g.class.publish(); ok {
		out.HasClass, out.Class = true, v
	}
	if v, ok := g.visible.publish(); ok {
		out.HasVisibleName, out.VisibleName = true, v
	}
	if v, ok := g.daily.publish(); ok {
		out.HasDailyTank, out.DailyTankJSON = true, v
	}
}

// valueMatches compares a wire value against the generator's JSON.
func valueMatches(got net.Value, want json.RawMessage) bool {
	var asNum float64
	if err := json.Unmarshal(want, &asNum); err == nil {
		return got.Kind == net.KindNumber && got.Num == asNum
	}
	var asStr string
	if err := json.Unmarshal(want, &asStr); err == nil {
		return got.Kind == net.KindString && got.Str == asStr
	}
	var tagged struct {
		Num string `json:"__num"`
	}
	if err := json.Unmarshal(want, &tagged); err == nil && tagged.Num == "nan" {
		return got.Kind == net.KindNumber && math.IsNaN(got.Num)
	}
	return false
}

func showValues(v []net.Value) string {
	out, _ := json.Marshal(v)
	return string(out)
}

func showRaw(v []json.RawMessage) string {
	out, _ := json.Marshal(v)
	return string(out)
}

// TestFloppyStates walks the three states a floppy can be in, because the whole
// HUD rests on them and the JS spells them with a null check rather than a flag.
func TestFloppyStates(t *testing.T) {
	var f floppyNum
	if _, ok := f.publish(); ok {
		t.Error("a fresh floppy published something; it holds null")
	}
	f.update(0)
	if v, ok := f.publish(); !ok || v != 0 {
		t.Errorf("the first update did not take: got %v, %v -- `value == null` is tested before the comparison", v, ok)
	}
	if _, ok := f.publish(); ok {
		t.Error("publishing twice sent the same value twice")
	}
	f.update(0)
	if _, ok := f.publish(); ok {
		t.Error("an unchanged value re-published")
	}
	f.update(1)
	if v, ok := f.publish(); !ok || v != 1 {
		t.Errorf("a changed value gave %v, %v", v, ok)
	}

	// NaN never equals itself, in JS or here, so a floppy holding one re-flags
	// on every update. That is the fps field's permanent state in this port.
	var n floppyNum
	for i := 0; i < 3; i++ {
		n.update(math.NaN())
		v, ok := n.publish()
		if !ok || !math.IsNaN(v) {
			t.Fatalf("round %d: NaN floppy gave %v, %v; it must re-publish every time", i, v, ok)
		}
	}
}

// TestFloppyMissingNeverPublishes verifies undefined floppies stay absent forever.
func TestFloppyMissingNeverPublishes(t *testing.T) {
	var f floppyStr
	for i := 0; i < 3; i++ {
		f.updateMissing()
		if v, ok := f.publish(); ok {
			t.Fatalf("round %d: an undefined floppy published %q", i, v)
		}
	}
	f.update("dreadnought_dreadsV1")
	if v, ok := f.publish(); !ok || v != "dreadnought_dreadsV1" {
		t.Errorf("got %q, %v", v, ok)
	}
}

// TestGUIUpdateIsAllocationFree verifies the settled HUD frame path allocates nothing.
func TestGUIUpdateIsAllocationFree(t *testing.T) {
	vectors := loadGUIVectors(t)
	var frame *guiFrame
	for i := range vectors.Cases {
		c := &vectors.Cases[i]
		if c.Name == "upgrades appear as the level rises" && len(c.Frames) > 0 {
			frame = &c.Frames[len(c.Frames)-1]
		}
	}
	if frame == nil {
		t.Skip("the upgrade case is gone from the vectors")
	}
	g := newGUIState()
	in := frame.Input.toGUIInput()
	for i := 0; i < 2; i++ {
		g.update(&in)
		var block net.GUIBlock
		publishInto(g, &block, in.teamColor)
	}
	var block net.GUIBlock
	got := testing.AllocsPerRun(100, func() {
		g.update(&in)
		block = net.GUIBlock{}
		publishInto(g, &block, in.teamColor)
	})
	if got != 0 {
		t.Errorf("a settled HUD frame allocates %v times, want 0", got)
	}
}
